on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 58 17 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: python:3.8
    steps:
    - uses: actions/checkout@v4
    - run: |
        apt-get update && apt-get install -y git && apt-get clean
        python -m pip install --upgrade pip
        pip install semgrep
        semgrep ci --supply-chain
